name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create directories
        run: mkdir -p src/main/resources/

      - name: Set up application.properties
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: List build directory recursively
        run: ls -alR build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packaged-application
          path: build/libs/*.jar

      - name: List build/libs directory
        run: ls -al build/libs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: packaged-application
          path: build

      - name: Create remote directory using SSH Action (optional)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ${{ secrets.REMOTE_DIR }}

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "build/wiko-0.0.1-SNAPSHOT.jar"
          target: "${{ secrets.REMOTE_DIR }}"

      - name: Deploy to AWS EC2
        env:
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          echo "REMOTE_DIR is: '$REMOTE_DIR'"
          
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
            echo "Stopping any running Java application..."
            pkill -f "java -jar ${REMOTE_DIR}/build/wiko-0.0.1-SNAPSHOT.jar" || echo "No running Java process found."
            sleep 5
            echo "Starting the application..."
            nohup java -jar "${REMOTE_DIR}/build/wiko-0.0.1-SNAPSHOT.jar" > nohup.out 2>&1 &
            echo "Deployment complete."
          EOF
